--- luaexpat-1.3.0/Makefile.orig	2014-04-03 01:30:37.000000000 +0200
+++ luaexpat-1.3.0/Makefile	2020-04-04 20:50:28.237001076 +0200
@@ -9,7 +9,7 @@
 T		= lxp
 LIBNAME		= $(T).so
 
-COMMON_CFLAGS	 = -g -pedantic -Wall -O2 -fPIC -DPIC -ansi
+COMMON_CFLAGS	 = -fPIC -DPIC
 LUA_INC		?= -I/usr/include/lua$(LUA_V)
 EXPAT_INC	?= -I/usr/include
 CF		 = $(LUA_INC) $(EXPAT_INC) $(COMMON_CFLAGS) $(CFLAGS)
